name: Workflow for Codecov lod_unit
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install .[test]
      - name: Run tests and collect coverage
        run: pytest --cov=lod_unit
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
